name: jupyter-lab
channels:
 - coecms
 - conda-forge
 - defaults
dependencies:
 - python>=3.8
 - jupyterhub
 - jupyterhub-base
 - requests
 - yaml
 - pip
 - pip:
     - git+https://github.com/jupyterhub/batchspawner.git
